import { 
  Heart, Headphones, Shield, DollarSign, Users, Bot, Plane, 
  Settings, Zap, Star, Globe, Phone, Mail, Calendar, FileText, 
  Briefcase, Home, Search, Bell, Lock, Key, Activity, Camera, 
  Music, Video, Map, Car, Truck, Building, School, Hospital, 
  Store, Utensils, Coffee, Code, Database, Cloud, Server, 
  Monitor, Smartphone, Laptop, Headset, Mic, Speaker, Wifi, 
  Battery, Power, Lightbulb, Sun, Moon, Sparkles, Crown, 
  Award, Trophy, Target, Flag, Gift, ShoppingCart, CreditCard, 
  Wallet, Clock 
} from "lucide-react";

export const getIconMap = () => ({
  Heart: <Heart className="w-10 h-10 text-white" />,
  Headphones: <Headphones className="w-10 h-10 text-white" />,
  Shield: <Shield className="w-10 h-10 text-white" />,
  DollarSign: <DollarSign className="w-10 h-10 text-white" />,
  Users: <Users className="w-10 h-10 text-white" />,
  Bot: <Bot className="w-10 h-10 text-white" />,
  Plane: <Plane className="w-10 h-10 text-white" />,
  Settings: <Settings className="w-10 h-10 text-white" />,
  Zap: <Zap className="w-10 h-10 text-white" />,
  Star: <Star className="w-10 h-10 text-white" />,
  Globe: <Globe className="w-10 h-10 text-white" />,
  Phone: <Phone className="w-10 h-10 text-white" />,
  Mail: <Mail className="w-10 h-10 text-white" />,
  Calendar: <Calendar className="w-10 h-10 text-white" />,
  FileText: <FileText className="w-10 h-10 text-white" />,
  Briefcase: <Briefcase className="w-10 h-10 text-white" />,
  Home: <Home className="w-10 h-10 text-white" />,
  Search: <Search className="w-10 h-10 text-white" />,
  Bell: <Bell className="w-10 h-10 text-white" />,
  Lock: <Lock className="w-10 h-10 text-white" />,
  Key: <Key className="w-10 h-10 text-white" />,
  Activity: <Activity className="w-10 h-10 text-white" />,
  Camera: <Camera className="w-10 h-10 text-white" />,
  Music: <Music className="w-10 h-10 text-white" />,
  Video: <Video className="w-10 h-10 text-white" />,
  Map: <Map className="w-10 h-10 text-white" />,
  Car: <Car className="w-10 h-10 text-white" />,
  Truck: <Truck className="w-10 h-10 text-white" />,
  Building: <Building className="w-10 h-10 text-white" />,
  School: <School className="w-10 h-10 text-white" />,
  Hospital: <Hospital className="w-10 h-10 text-white" />,
  Store: <Store className="w-10 h-10 text-white" />,
  Utensils: <Utensils className="w-10 h-10 text-white" />,
  Coffee: <Coffee className="w-10 h-10 text-white" />,
  Code: <Code className="w-10 h-10 text-white" />,
  Database: <Database className="w-10 h-10 text-white" />,
  Cloud: <Cloud className="w-10 h-10 text-white" />,
  Server: <Server className="w-10 h-10 text-white" />,
  Monitor: <Monitor className="w-10 h-10 text-white" />,
  Smartphone: <Smartphone className="w-10 h-10 text-white" />,
  Laptop: <Laptop className="w-10 h-10 text-white" />,
  Headset: <Headset className="w-10 h-10 text-white" />,
  Mic: <Mic className="w-10 h-10 text-white" />,
  Speaker: <Speaker className="w-10 h-10 text-white" />,
  Wifi: <Wifi className="w-10 h-10 text-white" />,
  Battery: <Battery className="w-10 h-10 text-white" />,
  Power: <Power className="w-10 h-10 text-white" />,
  Lightbulb: <Lightbulb className="w-10 h-10 text-white" />,
  Sun: <Sun className="w-10 h-10 text-white" />,
  Moon: <Moon className="w-10 h-10 text-white" />,
  Sparkles: <Sparkles className="w-10 h-10 text-white" />,
  Crown: <Crown className="w-10 h-10 text-white" />,
  Award: <Award className="w-10 h-10 text-white" />,
  Trophy: <Trophy className="w-10 h-10 text-white" />,
  Target: <Target className="w-10 h-10 text-white" />,
  Flag: <Flag className="w-10 h-10 text-white" />,
  Gift: <Gift className="w-10 h-10 text-white" />,
  ShoppingCart: <ShoppingCart className="w-10 h-10 text-white" />,
  CreditCard: <CreditCard className="w-10 h-10 text-white" />,
  Wallet: <Wallet className="w-10 h-10 text-white" />,
  Clock: <Clock className="w-10 h-10 text-white" />
});

export const getIconComponent = (iconName: string) => {
  const iconMap = getIconMap();
  return iconMap[iconName as keyof typeof iconMap] || <Bot className="w-10 h-10 text-white" />;
};
