"""
NiCE + Cognigy response to Ralph Lauren Contact Center Technology RFP — v2
Row-by-row bespoke responses. Every row has a unique answer.
"""
import openpyxl

INPUT  = "/Users/Adam.Boyle/Downloads/Attachment 2_Ralph Lauren Contact Center Technology RFP Vendor Requirements_Questionnaire_Pricing.xlsx"
OUTPUT = "/Users/Adam.Boyle/Downloads/NiCE Response - Ralph Lauren CCaaS RFP.xlsx"

wb = openpyxl.load_workbook(INPUT)

def fill(ws, row, col, val):
    ws.cell(row=row, column=col).value = val

# ── Sheet 2: AI & Virtual Agent Assessment ────────────────────────────────────
# yes=col6, resp=col7, cite=col8
AI_ROWS = {
    6:  ("Yes", "NICE Cognigy documents its own NLU models — intent definitions, training utterances, entity types, and confidence configuration — through the platform's admin interface and audit log. For third-party LLMs connected via the LLM Connector (OpenAI, Azure OpenAI, Anthropic, etc.), documentation is provided by those vendors and referenced in Cognigy's integration configuration.", "https://docs.cognigy.com/ai/administer/audit-events/"),
    7:  ("Yes", "NICE Cognigy logs every virtual agent interaction with intent classification, confidence score, matched entities, and the conversation path taken — providing a clear record of how NLU-driven decisions were reached. For LLM-generated responses (via connected providers such as Azure OpenAI or Anthropic), Cognigy records the prompt sent and the response received; the internal reasoning of the LLM itself is not exposed, consistent with how all LLM providers operate.", "https://docs.cognigy.com/ai/administer/audit-events/"),
    8:  ("Yes", "NICE Cognigy's NLU models — used for intent classification and entity extraction — can be trained, tested, and evaluated within the platform. The Intent Trainer shows misclassification rates, confidence distributions, and utterance coverage. For third-party LLMs connected to the platform, training and validation are handled by those providers; Cognigy does not retrain external models.", "https://docs.cognigy.com/ai/platform-features/nlu/intents/intent-trainer"),
    9:  ("Partial", "NICE Cognigy's NLU analytics expose intent distribution and confidence metrics that can surface bias in training data — for example, underrepresentation of certain language patterns. Bias evaluation for third-party LLMs (OpenAI, Anthropic, etc.) is the responsibility of those providers; customers select their LLM provider based on the provider's own AI ethics and bias policies.", "https://docs.cognigy.com/insights/dashboards/nlu-performance/"),
    10: ("Yes", "NICE Cognigy handles automated customer interactions across voice, chat, and IVR using its own NLU engine for intent classification and Voice Gateway for SIP/media handling. When escalation is needed, the handover protocol transfers the full conversation context to NICE CXone's ACD for agent assignment.", "https://www.cognigy.com/platform/cognigy-voice-gateway"),
    11: ("Yes", "NICE CXone SmartReach — acquired via LiveVox (2024) — delivers proactive omnichannel outbound campaigns across voice, SMS, email, and WhatsApp. Event-triggered campaigns (abandoned cart follow-up, delivery updates, return authorisations) fire from CRM or OMS events via the SmartReach campaign engine. TCPA/CTIA compliance and consent management are built in.", "https://www.nice.com/products/cxone-smartreach"),
    12: ("Yes", "Routing of outbound interactions to live agents is handled by NICE CXone's ACD engine, with intelligent queue management and IVR-to-agent handoff workflows. The native integration between NICE Cognigy and CXone ensures context is preserved at every transfer.", "https://www.cognigy.com/platform/cognigy-voice-gateway"),
    13: ("Yes", "NICE Cognigy supports chatbot deployment across web, mobile, and messaging channels using its flow-based dialogue engine and NLU. NICE Cognigy Webchat v3 meets WCAG 2.1 AA accessibility standards (audited July 2024).", "https://docs.cognigy.com/webchat/v3/overview"),
    14: ("Yes", "Natural language voicebots that fully replace traditional IVR menus are built and deployed through NICE Cognigy's Voice Gateway and visual flow builder. Complex conversational experiences require no custom code.", "https://www.cognigy.com/platform/cognigy-voice-gateway"),
    15: ("Yes", "Automation of complex customer inquiries is driven by NICE Cognigy's NLU engine, which uses 28 dedicated language models to classify intent and extract entities with high accuracy. NICE Cognigy's Intent Trainer continuously refines model accuracy using live conversation data.", "https://docs.cognigy.com/ai/empower/nlu/language-support/"),
    16: ("Yes", "Third-party NLU engines — including Google Dialogflow, Amazon Lex, and IBM Watson Assistant — are connected through NICE Cognigy's NLU Connector framework. Organisations can route to these engines alongside or instead of NICE Cognigy's native NLU.", "https://docs.cognigy.com/ai/platform-features/nlu/external/nlu-connector-reference/all-nlu-connectors"),
    17: ("Yes", "Directed dialogue and keyword-guided speech recognition — where customers use natural language rather than DTMF — are enabled through NICE Cognigy's Voice Gateway. This replaces legacy menu navigation with conversational interaction patterns.", "https://www.cognigy.com/platform/cognigy-voice-gateway"),
    18: ("Yes", "NICE Cognigy Agent Copilot displays real-time suggestions, surfaces knowledge articles, and can generate draft replies during live interactions. Draft reply generation uses a configured third-party LLM (e.g. Azure OpenAI or Anthropic) — the organisation selects and controls which LLM provider is used.", "https://docs.cognigy.com/agent-copilot/overview"),
    19: ("Yes", "Event-driven customer notifications — including sentiment shifts, intent escalations, and workflow milestones — are orchestrated through NICE CXone's real-time event engine. Contextual alerts are delivered within the omnichannel platform.", "https://www.nice.com/products/cxone"),
    20: ("Yes", "NICE CXone Interaction Analytics transcribes voice interactions and runs NLP-based topic detection, sentiment scoring, and category tagging across 100% of calls. Automated call summaries are available when a third-party LLM is configured; topic and sentiment analysis are native to the NICE CXone analytics engine.", "https://www.nice.com/products/interaction-analytics"),
    21: ("Yes", "NICE CXone Interaction Analytics applies NLP-based sentiment analysis and categorisation across chat, email, and transcribed voice interactions. Conversation summarisation is available via NICE Cognigy's LLM integration framework, which routes to a customer-configured third-party LLM (Azure OpenAI, OpenAI, Anthropic, etc.).", "https://www.nice.com/products/interaction-analytics"),
    22: ("Yes", "Automated quality scoring of voice, chat, and text interactions using behavioural analytics is delivered by NICE CXone Auto QA. Configurable scorecards apply consistently at 100% interaction coverage, eliminating sampling bias.", "https://www.nice.com/products/quality-management"),
    23: ("Yes", "Multi-language speech-to-text — including sentiment analysis across languages — is achieved through NICE Cognigy's Voice Gateway integrations with Deepgram Nova-3, Google STT, Microsoft Azure STT, and Amazon Transcribe. STT providers are configurable per deployment.", "https://docs.cognigy.com/voice-gateway/webapp/speech-services"),
    24: ("Partial", "Speaker diarisation for multi-channel recordings is available through supported STT providers (Azure Speech Services, Google Cloud) integrated via NICE Cognigy's Voice Gateway. NICE provides the orchestration and channel attribution layer on top of the diarisation output.", "https://docs.cognigy.com/voice-gateway/webapp/speech-services"),
    25: ("Yes", "Custom vocabulary and pronunciation tuning for brand names and domain terminology is supported via the STT provider's own model customisation features (e.g. Deepgram custom models, Azure custom speech). NICE Cognigy's Voice Gateway configuration specifies which STT provider and model variant to use per deployment.", "https://www.cognigy.com/platform/cognigy-voice-gateway"),
    26: ("Yes", "NICE Cognigy supports post-call note generation by passing STT transcripts to a configured third-party LLM (Azure OpenAI, OpenAI, Anthropic, or similar) with customisable prompt templates. The summarisation logic and prompts are controlled by the customer; NICE Cognigy handles the orchestration and storage.", "https://docs.cognigy.com/ai/empower/llms/overview/"),
    27: ("Yes", "NICE CXone automatically transcribes text-based interactions from chat, email, and messaging channels and structures them as searchable conversation records. This enables downstream compliance auditing and analytics without manual processing.", "https://docs.cognigy.com/webchat/v3/overview"),
    28: ("Yes", "Both voice and text interactions are transcribed by NICE CXone's analytics engine, with full-text search across transcripts including sentiment, intent, and topic extraction. Compliance risk indicators are flagged automatically.", "https://www.nice.com/products/interaction-analytics"),
    29: ("Yes", "NICE Cognigy's Voice Gateway processes audio in formats including WAV, MP3, and Opus, with built-in background noise detection and multi-speaker support. Audio quality is maintained through cloud-native processing regardless of geographic routing.", "https://www.cognigy.com/platform/cognigy-voice-gateway"),
    30: ("Yes", "Text-to-speech output is delivered through NICE Cognigy's Voice Gateway TTS integrations, supporting ElevenLabs, Microsoft Azure Neural TTS, Google WaveNet, and Nuance. Organisations select TTS provider and voice persona per interaction type.", "https://docs.cognigy.com/voice-gateway/webapp/speech-services"),
    31: ("Yes", "NICE Cognigy's Voice Gateway converts system-generated text — for IVR prompts and bot responses — into natural-sounding speech through its TTS integration layer. Voice personas are configurable by use case, language, and brand style requirements.", "https://docs.cognigy.com/voice-gateway/webapp/speech-services"),
    32: ("Yes", "Simultaneous deployment of multiple TTS engines with prioritisation rules is supported by NICE Cognigy's Voice Gateway. Organisations can run parallel providers for A/B testing and match voice characteristics to brand identity.", "https://docs.cognigy.com/voice-gateway/webapp/speech-services"),
    33: ("Yes", "Readable, searchable, and timestamped call transcripts are generated automatically for all voice interactions processed through NICE Cognigy's Voice Gateway. Transcripts are indexed, full-text searchable, and exportable for compliance purposes.", "https://www.nice.com/info/real-time-transcription-for-call-centers"),
    34: ("Yes", "Managing and updating AI models is done through NICE Cognigy's Intent Trainer and NLU admin interface, with version tracking, staging environments, and rollback capabilities. Training pipelines support scheduled and manual retraining cycles.", "https://docs.cognigy.com/ai/platform-features/nlu/intents/intent-trainer"),
    35: ("Yes", "Multi-turn conversations requiring complex reasoning are handled by NICE Cognigy's stateful dialogue management engine and LLM integration layer. Session context, user intent history, and extracted entities persist across every turn.", "https://docs.cognigy.com/ai/empower/agentic-ai/overview/"),
    36: ("Yes", "Escalation to live CSRs is managed through NICE Cognigy's built-in handover protocol, which queues interactions to NICE CXone's ACD with the full transcript, intent history, and extracted entities pre-populated. Agent greeting scripts are contextually triggered.", "https://docs.cognigy.com/ai/escalate/handovers"),
    37: ("Partial", "Continuous learning from live interaction data is supported through NICE Cognigy's Intent Trainer, which surfaces misclassified utterances for human review and retraining. Active reinforcement learning pipelines require optional third-party ML tooling for advanced model tuning.", "https://docs.cognigy.com/ai/platform-features/nlu/intents/intent-trainer"),
    38: ("Yes", "Full NLU model governance — including training, version control, staging, and deployment with role-based access — is managed through NICE Cognigy's admin interface. Production deployment requires approval workflows, and all model changes are audit-logged.", "https://docs.cognigy.com/ai/platform-features/nlu/intents/intent-trainer"),
    39: ("Yes", "NICE Cognigy handles free-form customer input through its NLU engine (for intent/entity classification) and optionally via a connected third-party LLM for open-ended generative responses. No rigid menu structure is required; the combination of trained NLU and LLM-backed dialogue covers both structured and unstructured interactions.", "https://docs.cognigy.com/ai/empower/nlu/language-support/"),
    40: ("Yes", "Large language model integrations in NICE Cognigy include Azure OpenAI, OpenAI GPT-4, Anthropic Claude, Google Gemini, and Amazon Bedrock/Nova. Organisations select providers based on data residency, latency, and model capability requirements.", "https://docs.cognigy.com/ai/empower/llms/overview/"),
    41: ("Yes", "NICE Cognigy does not host LLMs itself. However, any OpenAI-compatible model endpoint — including fine-tuned models hosted by the customer or a third party — can be registered in NICE Cognigy's LLM Connector and used within conversation flows. This covers self-hosted open-source models (e.g. Llama), Azure-hosted fine-tunes, and private endpoints.", "https://docs.cognigy.com/ai/empower/llms/overview/"),
    42: ("Yes", "NICE Cognigy Knowledge AI handles ingestion, chunking, embedding, and retrieval of knowledge content (PDFs, URLs, structured documents). At runtime, relevant passages are retrieved by Cognigy's own RAG pipeline and passed as context to a customer-configured third-party LLM, which generates the final response. Source citations are returned alongside answers.", "https://www.cognigy.com/platform/cognigy-knowledge-ai"),
    43: ("Yes", "NICE Cognigy improves knowledge base content by analysing live conversations for intent patterns, knowledge gaps, and escalation triggers. These insights feed directly into Agent Copilot recommendations and knowledge article update workflows.", "https://docs.cognigy.com/agent-copilot/overview"),
    44: ("Yes", "NICE Cognigy's NLU engine includes dedicated trained models for English and French with full intent/entity feature parity between both languages — no third-party NLU licensing is required. TTS and STT are provided by third-party integrations (Deepgram, ElevenLabs, Azure, Google) and all support both English and French without capability degradation.", "https://docs.cognigy.com/ai/empower/nlu/language-support/"),
    45: ("Yes", "NICE Cognigy provides automated translation of voice and chat interactions through its integration with translation services layered on STT/ASR. Customers interact in their native language while agents receive translated text in real time.", "https://docs.cognigy.com/ai/build/translation-and-localization/auto-translation/"),
    46: ("Yes", "Automatic language detection and manual override for routing are built into NICE Cognigy's detection pipeline. Voice interactions are detected at the STT layer; chat interactions at the NLU layer — both route automatically to the correct locale configuration.", "https://docs.cognigy.com/ai/empower/nlu/language-support/"),
    47: ("Yes", "Consistent user experience across all 100+ supported languages is delivered through NICE Cognigy's localised NLU models, language-specific voice personas, and region-specific compliance configurations. System prompts and UI elements scale across all locales.", "https://docs.cognigy.com/ai/empower/nlu/language-support/"),
    48: ("Yes", "Language usage and performance reporting — including volume by language, sentiment trends, and resolution rates — is available through NICE CXone's analytics dashboards. Multilingual performance comparisons are supported across regions.", "https://docs.cognigy.com/insights/dashboards/nlu-performance/"),
    49: ("Yes", "NICE CXone's compliance framework supports region-specific regulatory requirements per language, including GDPR (EU), HIPAA (US), and HITRUST CSF. Data residency is independently configurable per region, and language-specific interaction flows can embed locale-appropriate consent and disclosure rules.", "https://www.nice.com/company/trust-center"),
    50: ("Yes", "Third-party NLU engine integration via NICE Cognigy's NLU Connector framework supports Google Dialogflow, Amazon Lex, IBM Watson Assistant, and custom REST-compatible NLU endpoints. Hybrid NLU routing is supported within a single conversation flow.", "https://docs.cognigy.com/ai/platform-features/nlu/external/nlu-connector-reference/all-nlu-connectors"),
    51: ("Yes", "Third-party TTS provider integration — including ElevenLabs, Azure Neural TTS, Google WaveNet, and Nuance — is managed through NICE Cognigy's Voice Gateway. Multiple TTS providers can run simultaneously with automated failover rules.", "https://docs.cognigy.com/voice-gateway/webapp/speech-services"),
}

# ── Sheet 3: Data Assessment ───────────────────────────────────────────────────
# yes=col6, resp=col7, cite=col8
DATA_ROWS = {
    6:  ("Yes", "NICE CXone ensures all interaction data is immediately available for real-time and historical analysis through its Data Stream API and analytics portal. High-availability mechanisms and multi-AZ replication guarantee continuous data access.", "https://www.nice.com/products/cxone"),
    7:  ("Yes", "NICE CXone Interaction Analytics enables full-content search across interaction data, supporting keyword, phrase, topic, and custom tag filtering. Results are paginated and available for export within seconds of query submission.", "https://www.nice.com/products/interaction-analytics"),
    8:  ("Yes", "NICE CXone's reporting engine produces data outputs in CSV, Excel, JSON, and PDF formats with scheduled delivery to SFTP, S3, and Azure Blob. CXexchange's 150+ connectors enable direct integration with enterprise BI platforms.", "https://www.nice.com/products/reporting"),
    9:  ("Yes", "NICE CXone captures and links cross-channel context at the customer identifier level, preserving IVR traversal, bot conversation, and CRM interaction records in a single unified timeline. API-based retrieval makes this context available to all integrated systems.", "https://www.nice.com/products/digital-voice-channels"),
    10: ("Yes", "NICE CXone enforces role-based access control restricting data visibility at the report, dashboard, and API level. Supervisors view team data; agents see only their own records; custom roles are configurable through the admin portal.", "https://www.nice.com/info/data-sharing-and-access-management-in-contact-centers"),
    11: ("Yes", "NICE CXone's certified data handling framework maintains compliance with HIPAA, GDPR, PCI DSS Level 1, and CCPA. SOC 2 Type II, ISO 27001, HITRUST CSF, and FedRAMP Moderate certifications are held and renewed annually.", "https://www.nice.com/company/trust-center"),
    12: ("Yes", "NICE Cognigy returns the top-ranked intent, confidence score, and matched entities for every NLU decision, giving administrators a clear view of how AI conclusions were reached. RAG-based responses include the exact source document and passage used.", "https://docs.cognigy.com/insights/dashboards/nlu-performance/"),
    13: ("Yes", "NICE CXone maintains comprehensive audit trails logging every user action, configuration change, and AI decision with timestamp, user identity, and source IP. Logs are SIEM-compatible and exportable to Splunk, Datadog, or Syslog.", "https://www.nice.com/products/security-and-compliance"),
    14: ("Yes", "NICE Cognigy surfaces structured model inputs and outputs — intent names, entity values, confidence scores, and RAG citations — in conversation logs in human-readable format. This satisfies explainability requirements for GDPR Article 22 (automated decision-making).", "https://docs.cognigy.com/insights/dashboards/nlu-performance/"),
    15: ("Yes", "NICE Cognigy communicates model confidence limitations explicitly through intent confidence scores and threshold-based fallback routing. Low-confidence interactions are automatically escalated to live agents, with confidence distributions visible in the NLU analytics dashboard.", "https://docs.cognigy.com/insights/dashboards/nlu-performance/"),
    16: ("Yes", "NICE CXone and NICE Cognigy deliver explainability features satisfying key regulatory frameworks including GDPR (right to explanation), FCRA, and CCPA. Full interaction audit trails and AI decision logs are available for regulatory review and customer dispute resolution.", "https://www.nice.com/products/security-and-compliance"),
    17: ("Yes", "NICE CXone provides 100+ prebuilt interaction reports covering AHT, FCR, CSAT, abandonment rate, agent performance, and channel volume. Scheduled report delivery and drill-down from summary to individual interaction level are both supported.", "https://www.nice.com/products/reporting"),
    18: ("Yes", "NICE CXone's multi-channel reporting spans voice, chat, email, SMS, and bot interactions in a single unified data set. Cross-channel journey reports trace one customer across all touchpoints within and across sessions.", "https://www.nice.com/products/interaction-analytics"),
    19: ("Yes", "NICE CXone's advanced report filtering supports multi-dimensional criteria including date range, channel, agent, queue, team, sentiment, disposition, and custom attributes. Filtered views are saveable as reusable report templates.", "https://www.nice.com/products/reporting"),
    20: ("Yes", "NICE CXone's reporting portal and REST API enable both batch and on-demand export of interaction data in CSV, Excel, and JSON. Scheduled exports can be delivered automatically to enterprise data warehouse destinations.", "https://www.nice.com/products/open-cloud-platform/restful-apis"),
    21: ("Yes", "NICE CXone Interaction Analytics provides keyword, phrase, and topic search across recorded calls with timestamped results pinpointing relevant moments within recordings. QA reviewers can jump directly to flagged content without full playback.", "https://www.nice.com/products/interaction-analytics"),
    22: ("Yes", "NICE CXone's analytics module delivers customer journey mapping across all channels, showing channel sequences, handoff points, self-service paths, and resolution outcomes. Journey flows are visualised and exportable.", "https://www.nice.com/products/customer-journey-analytics"),
    23: ("Yes", "NICE CXone triggers post-interaction surveys — via IVR, SMS, or email — automatically at interaction close or manually by agents. NPS, CSAT, and CES scoring are supported, with survey results correlated to individual interaction records.", "https://www.nice.com/products/voice-of-the-customer"),
    24: ("Yes", "NICE CXone's drag-and-drop custom report builder allows business users to create ad-hoc reports on any interaction, agent, queue, or AI metric. Calculated fields, conditional formatting, and drill-down capabilities are included without IT support.", "https://www.nice.com/products/cx-analytics/reporting"),
    25: ("Yes", "NICE CXone Auto QA delivers compliance and fraud-risk flagging by applying configurable phrase and behaviour rules to automatically route high-risk interactions to QA queues for human review. Real-time alerts are sent to supervisors for critical violations.", "https://www.nice.com/products/quality-management"),
    26: ("Yes", "NICE CXone's speech and text analytics produce structured key-metric reports with consistent schema across all exports, ensuring downstream BI tools receive predictable data formats. Talk time, silence, overlap, and sentiment are extracted per interaction.", "https://www.nice.com/products/interaction-analytics"),
    27: ("Yes", "NICE CXone real-time dashboards display live agent, queue, and system metrics with configurable refresh rates. Supervisors see queue depth, agent states, AHT, SLA adherence, and channel volumes updated continuously.", "https://www.nice.com/products/reporting"),
    28: ("Yes", "NICE CXone delivers personalised real-time dashboard views — filtered by role, region, or skill group — configurable per user. KPI selections and layout preferences save per login, enabling each supervisor to monitor the metrics most relevant to their team.", "https://www.nice.com/platform/supervisor-workspace"),
    29: ("Yes", "NICE CXone consolidates live reporting across all contact centre functions — ACD, IVR, WFM, and AI bot activity — in its operational dashboards. A single view spans every channel and queue simultaneously.", "https://www.nice.com/products/reporting"),
    30: ("Yes", "NICE CXone natively supports granular time-interval reporting at 15-minute, 30-minute, hourly, and daily aggregations. Analysts can drill from high-level KPI summaries down to individual interaction records at any interval.", "https://www.nice.com/products/reporting"),
    31: ("Yes", "NICE CXone's IVR interaction monitoring tracks call routing decisions, menu navigation patterns, and DTMF input sequences in real time. Funnel analysis identifies abandonment points and self-service containment rates.", "https://www.nice.com/products/digital-and-self-service"),
    32: ("Yes", "NICE CXone's distributed cloud architecture supports unlimited concurrent real-time report users without performance degradation. Enterprise deployments with thousands of simultaneous supervisors are handled through horizontal scaling.", "https://www.nice.com/products/open-cloud-platform"),
    33: ("Yes", "NICE CXone's threshold-based action triggers fire SMS alerts, email notifications, or in-app escalations when operational metrics breach configured limits. Event handlers can automatically trigger routing changes, staffing adjustments, or supervisor notifications.", "https://www.nice.com/platform/supervisor-workspace"),
    34: ("Yes", "NICE CXone's REST API and Data Stream API enable real-time integration with external data sources for enriching operational reports with third-party metrics. Bi-directional data exchange supports CRM, ERP, and workforce management system integration.", "https://www.nice.com/products/open-cloud-platform/restful-apis"),
    35: ("Yes", "NICE CXone connects to 150+ enterprise systems through CXexchange, including Salesforce, Dynamics 365, ServiceNow, case management, ERP, and OMS platforms. Customer transaction history and profile data automatically populate the agent desktop at interaction start.", "https://www.nice.com/products/crm-integrations"),
    36: ("Yes", "NICE CXone supports real-time API synchronisation and scheduled batch data transfers concurrently. Real-time webhooks handle low-latency updates while batch SFTP/S3 feeds serve data warehouse ingestion pipelines.", "https://www.nice.com/products/open-cloud-platform/restful-apis"),
    37: ("Yes", "NICE CXone's REST API gives external applications on-demand query access to interaction data and business metrics. OpenAPI (Swagger) documentation covers all endpoints, authentication patterns, and response schemas.", "https://www.nice.com/products/open-cloud-platform/restful-apis"),
    38: ("Yes", "NICE CXone's webhook framework enables sharing of custom business logic calculations and derived metrics to downstream systems. Outbound event payloads are configurable per event type and include full interaction context.", "https://www.nice.com/products/integrations-developer-tools-apis"),
    39: ("Yes", "NICE CXone provides SOAP and REST web service interfaces supporting bidirectional data exchange with external applications. Standard XML/JSON payloads and industry-standard authentication schemes ensure broad compatibility.", "https://www.nice.com/products/open-cloud-platform/restful-apis"),
    40: ("Yes", "NICE CXone provides direct connectivity to external databases, cloud data warehouses, and BI platforms through the Data Stream API and CXexchange connectors. SQL-level query access to third-party data sources is supported for report enrichment.", "https://www.nice.com/products/open-cloud-platform/restful-apis"),
    41: ("Partial", "NICE CXone supports phone number validation and carrier lookup for outbound SMS through integration with third-party telecommunications APIs. Connectivity to carrier lookup providers is enabled via NICE CXone's REST API framework.", "https://www.nice.com/resources/outbound-calling-faces-changes-complex-compliance-requirements"),
    42: ("Yes", "NICE CXone's event handler logic uses configurable webhooks, API callbacks, and conditional business rules to manage integration events. Retry logic, payload encryption, and delivery confirmation are included.", "https://www.nice.com/products/integrations-developer-tools-apis"),
    43: ("Yes", "NICE CXone and NICE Cognigy publish comprehensive API documentation with code samples, SDK references, and authentication guides for all platform services. Developer support is available through NICE's developer portal and CXexchange ecosystem.", "https://www.nice.com/products/open-cloud-platform/restful-apis"),
    44: ("Yes", "NICE CXone's SMS provider integration supports major carriers and messaging platforms through REST API and webhook configurations. Two-way SMS capabilities for outbound notification and customer reply handling are included.", "https://www.nice.com/products/social-chat-and-messaging"),
}

# ── Sheet 4: Functional Assessment ────────────────────────────────────────────
# yes=col6, resp=col7, cite=col8
FUNC_ROWS = {
    6:  ("Yes", "NICE CXone orchestrates end-to-end customer journeys across all supported channels with full context preservation at every handoff point. Voice, chat, email, SMS, WhatsApp, and social interactions are unified under a single routing and reporting engine.", "https://www.nice.com/products/cxone"),
    7:  ("Yes", "Context is automatically preserved across channel transitions in NICE CXone through the unified customer profile and NICE Cognigy's Context object. Agents receive pre-populated screens with prior interaction history, intent, and extracted entities when a customer switches channels.", "https://docs.cognigy.com/ai/empower/agentic-ai/overview/"),
    8:  ("Yes", "NICE CXone SmartReach delivers omnichannel proactive outbound campaign management across voice, SMS, email, and WhatsApp. Campaign supervisors configure dialing modes (predictive, progressive, preview), pacing targets, contact lists, and attempt controls from a centralised Attempt Supervisor console with real-time productivity dashboards.", "https://www.nice.com/products/cxone-smartreach"),
    9:  ("Yes", "Complex business rule configuration — including priority queuing, customer-tier routing, time-of-day logic, and skill-based rules — is managed in NICE CXone's rules engine through a no-code admin interface. Rules take effect in real time without platform downtime.", "https://www.nice.com/products/omnichannel-routing"),
    10: ("Yes", "Concurrent multi-channel handling — with configurable per-agent limits — is supported across chat, email, and messaging in NICE CXone. Dynamic concurrency adjustments can be triggered by interaction complexity, queue depth, or time-of-day rules.", "https://www.nice.com/products/social-chat-and-messaging"),
    11: ("Yes", "Mid-interaction channel switching with full context handover is built into NICE CXone. A customer who transitions from voice to chat, for example, does not need to re-authenticate or repeat information — the full conversation context travels with them.", "https://www.nice.com/glossary/unified-cx-across-channels"),
    12: ("Yes", "Launching digital channels from an active voice interaction — such as sending a secure link via SMS — is supported through NICE CXone's channel orchestration capabilities. The agent maintains the voice connection while the digital session is initiated in parallel.", "https://www.nice.com/products/cxone"),
    13: ("Yes", "Simultaneous multi-channel support within a single session — for example, voice plus co-browse or chat — is available through NICE CXone. The unified agent desktop manages concurrent channel streams without context loss.", "https://www.nice.com/products/cxone"),
    14: ("Yes", "Backend CRM and OMS integration during interactions is enabled through NICE CXone's 150+ CXexchange connectors and REST API framework. Salesforce, Dynamics 365, ServiceNow, and custom systems are all supported with real-time data lookup.", "https://www.nice.com/products/integrations-developer-tools-apis"),
    15: ("Yes", "Email channel integration with routing, queuing, and automated response management is built into NICE CXone. AI-powered email classification routes inbound messages to the correct skill queue and can trigger auto-acknowledgement and template responses.", "https://www.nice.com/products/social-chat-and-messaging"),
    16: ("Yes", "NICE CXone's AI-powered routing engine evaluates intent (classified by NICE Cognigy), customer value, agent skills, and live queue conditions to make optimal assignment decisions in real time. Routing models are tunable per skill group.", "https://www.nice.com/products/ai-routing"),
    17: ("Yes", "Dynamic routing that adjusts continuously to real-time conditions — including queue depth, agent availability, predicted handle time, and customer priority — is native to NICE CXone. Routing logic can be updated live without platform downtime.", "https://www.nice.com/products/omnichannel-routing"),
    18: ("Yes", "Agent affinity and last-agent routing are configurable at the queue level in NICE CXone. Affinity decay thresholds ensure preferred-agent requests fall back to the general pool after a defined wait period, balancing personalisation against service speed.", "https://www.nice.com/resources/nice-cxone-mpower-omnichannel-routing-brochure"),
    19: ("Yes", "Full interaction audit trails with context logs — capturing all data transformations, routing decisions, and customer context changes — are maintained throughout the NICE CXone interaction lifecycle. Records are exportable and SIEM-compatible.", "https://www.nice.com/products/security-and-compliance"),
    20: ("Yes", "Inbound voice call handling with full ACD, IVR, call recording, and agent desktop screen-pop is core to NICE CXone. SIP trunking, PSTN fallback, and E.164 number management are all supported.", "https://www.nice.com/resources/nice-cxone-automatic-contact-distributor-acd"),
    21: ("Yes", "CRM and OMS system integration at the channel layer enables NICE CXone to surface real-time customer data on agent screens. Salesforce, Dynamics 365, and ServiceNow are available as managed connectors with bidirectional sync.", "https://www.nice.com/products/crm-integrations"),
    22: ("Yes", "Digital channel breadth in NICE CXone covers SMS, WhatsApp, Apple Messages for Business, Facebook Messenger, Instagram, web chat, and RCS. All channels are managed through a single agent desktop interface with unified routing.", "https://www.nice.com/products/social-chat-and-messaging"),
    23: ("Yes", "NICE Cognigy Webchat v3 powers rich web chat experiences including carousels, quick replies, file upload, and structured forms. It is WCAG 2.1 AA audited (July 2024) and aligned with WCAG 2.2 AA, ensuring accessibility compliance.", "https://docs.cognigy.com/webchat/v3/overview"),
    24: ("Yes", "Automated email handling — including intelligent routing, acknowledgement, template responses, and AI-generated reply drafts — is provided by NICE CXone. NICE Cognigy can fully automate routine email interactions without agent involvement.", "https://www.nice.com/glossary/ai-email-automation-for-customer-support"),
    25: ("Yes", "IP address blocking for chat and phone number blocking for voice are configurable in NICE CXone's security admin panel. Block lists are enforced in real time and configurable by fraud or compliance teams without engineering support.", "https://www.nice.com/products/security-and-compliance"),
    26: ("Yes", "Multi-channel WFM forecasting and scheduling — at 15-minute intervals across voice, chat, email, and messaging — is delivered by NICE CXone WFM. Automated schedule generation respects skills, labour rules, agent preferences, and service level targets.", "https://www.nice.com/products/workforce-management"),
    27: ("Yes", "Agent self-scheduling through NICE CXone WFM's Shift Bidding feature enables staff to request schedule changes, pick up open shifts, and submit time-off requests within configurable constraints. Approval workflows are automated or supervisor-controlled.", "https://www.nice.com/products/workforce-management"),
    28: ("Yes", "Erlang C, regression analysis, and pattern-matching algorithms power NICE CXone WFM's forecasting engine. Historical data from CXone's ACD and third-party systems feeds multi-channel volume predictions accurate to 15-minute intervals.", "https://www.nice.com/products/workforce-management"),
    29: ("Yes", "Customisable performance dashboards with real-time KPI tracking — including AHT, CSAT, FCR, quality scores, and channel-specific metrics — are provided for supervisors and agents in NICE CXone. Role-based views are configurable per user group.", "https://www.nice.com/products/cx-analytics/reporting"),
    30: ("Yes", "Real-time adherence monitoring with automated supervisor alerts is built into NICE CXone WFM. Agents' actual state is continuously compared against scheduled state, with threshold-breach notifications delivered in-app, via SMS, or by email.", "https://www.nice.com/products/workforce-management"),
    31: ("Yes", "Supervisor coaching tools in NICE CXone surface AI-identified coaching opportunities from Auto QA evaluations, with recommended content and integrated performance review workflows. Trend analysis identifies improvement patterns across agent cohorts.", "https://www.nice.com/products/quality-management"),
    32: ("Yes", "Multi-factor authentication for both agents and customers is supported natively across all NICE CXone service channels. Supported factors include TOTP, push notifications, SMS OTP, and hardware tokens via SAML IdP integration.", "https://www.nice.com/blog/rta-what-is-multi-factor-authentication"),
    33: ("Yes", "SSO integration with major enterprise identity providers — including Okta, Azure AD, Ping Identity, and OneLogin — is enabled through NICE CXone's SAML 2.0 and OAuth 2.0/OIDC support. SCIM 2.0 automates user provisioning and deprovisioning.", "https://www.nice.com/products/security-and-compliance"),
    34: ("Partial", "NICE CXone integrates certified voice biometric providers enabling passive customer enrolment and fraudster voiceprint detection during interactions. Provider certification is through NICE's established partner programme; specific provider options are discussed during solution design.", "https://www.nice.com/info/voice-biometrics-for-contact-centers"),
    35: ("Yes", "One-hundred percent multi-channel recording — covering voice, chat transcripts, email threads, and synchronised screen recordings — is provided by NICE CXone. PCI DSS pause/resume masks payment card data automatically, and all recordings are retained per contractual terms.", "https://www.nice.com/products/recording"),
    36: ("Yes", "Contextual search across recorded calls — by keyword, phrase, sentiment, topic, or speaker — is powered by NICE CXone Interaction Analytics. Timestamped results enable QA reviewers to navigate directly to relevant moments without full playback.", "https://www.nice.com/products/interaction-analytics"),
    37: ("Yes", "Personalised self-service and agent-assisted experiences are enabled through NICE Cognigy's conversational AI, which surfaces customer profile data, order history, and loyalty tier from integrated CRM systems at the start of every interaction.", "https://www.cognigy.com/platform/cognigy-ai"),
    38: ("Yes", "NICE CXone SmartReach includes full TCPA, CTIA, and CAN-SPAM compliance automation: time-zone-aware dialing windows, DNC list scrubbing, embedded consent management, suppression list enforcement, and consent audit storage with interaction records.", "https://www.nice.com/products/cxone-smartreach"),
    39: ("Yes", "NICE CXone SmartReach's predictive dialing pacing algorithms maximise agent occupancy while automatically respecting regulatory abandon rate thresholds. Pacing adjusts in real time to contact rate, agent availability, and campaign-specific compliance parameters.", "https://www.nice.com/products/cxone-smartreach"),
    40: ("Yes", "NICE CXone SmartReach includes configurable answering machine detection. AMD logic distinguishes live answers from voicemail with tunable accuracy per campaign, supporting message-leave delivery, compliance logging, and campaign-specific handling rules.", "https://www.nice.com/products/cxone-smartreach"),
    41: ("Yes", "NICE CXone SmartReach delivers high-throughput predictive dialing with centralised campaign management. Predictive algorithms minimise agent idle time while maintaining compliance thresholds, with real-time campaign dashboards for supervisor oversight and mid-flight pacing adjustments.", "https://www.nice.com/products/cxone-smartreach"),
    42: ("Yes", "Inbound and outbound contact blending across all channels is orchestrated by NICE CXone's unified ACD. Priority-based queue management and real-time allocation optimise agent utilisation across inbound service and outbound campaign work simultaneously.", "https://www.nice.com/products/cxone"),
    43: ("Yes", "NICE CXone natively stores interaction history and customer profile data across all channels, providing a unified contact record for voice, chat, email, SMS, and social interactions. For organisations without an existing enterprise CRM, NICE CXone can serve as the system of record for contact-centre-side customer data, with REST APIs available for integration with OMS, ecommerce, and data warehouse systems.", "https://www.nice.com/products/crm-integrations"),
    44: ("Partial", "Profile governance, merge/unmerge, and household management require integration with a CRM or customer data platform. NICE CXone enables audit trails of all profile changes and integrates with Salesforce, Dynamics, and CDPs to support identity resolution workflows.", "https://www.nice.com/products/crm-integrations"),
    45: ("Partial", "Chronological cross-channel interaction timelines linked to order and case history require integration with OMS and case management systems. NICE CXone provides the channel-side interaction history and context; full timeline views are assembled via Salesforce or ServiceNow integration.", "https://www.nice.com/products/crm-integrations"),
    46: ("Partial", "Customer preference management including style, language, and VIC attributes requires a CRM or CDP integration. NICE CXone reads and applies preferences from integrated CRM systems to influence routing decisions, personalised greetings, and agent screen-pop content.", "https://www.nice.com/products/crm-integrations"),
    47: ("Yes", "Case creation, escalation, SLA tracking, and resolution management are enabled through NICE CXone's case management framework and its certified integrations with Salesforce Service Cloud and ServiceNow. Embedded case workflows appear within the unified agent desktop.", "https://www.nice.com/products/crm-integrations"),
    48: ("Partial", "Order status, return processing, and exchange management are handled via NICE Cognigy's API tool-calling capability, which queries the OMS at runtime — including IBM Sterling OMS, which NICE Cognigy integrates with through REST API. Return eligibility rules and refund calculations remain in Sterling and are surfaced to agents and bots through the integration.", "https://docs.cognigy.com/ai/for-developers/developers/api-and-cli"),
    49: ("Yes", "Automatic intent tagging at interaction start is powered by NICE Cognigy's NLU engine, which classifies intent and passes tags to NICE CXone as routing attributes. This drives skills-based routing, knowledge surfacing, and downstream case categorisation without manual agent input.", "https://docs.cognigy.com/ai/platform-features/nlu/intents/intent-trainer"),
    50: ("Partial", "Policy eligibility evaluation and exception handling guidance requires integration with the policy rules engine or CRM. NICE CXone supports this through workflow automation and NICE Cognigy's Knowledge AI, which surfaces relevant policy content based on customer intent.", "https://www.cognigy.com/platform/cognigy-knowledge-ai"),
    51: ("Partial", "Store, boutique, and appointment context for clienteling requires integration with retail store and appointment management systems. NICE CXone surfaces store-linked data through Salesforce or custom API integration, with NICE Cognigy driving the conversational interface.", "https://www.nice.com/products/crm-integrations"),
    52: ("Partial", "Real-time inventory, availability, and waitlist data are surfaced during bot conversations through NICE Cognigy's API tool-calling capability, which queries the inventory management system at runtime. Enrolment and fulfilment actions require write-back integration with the existing inventory platform.", "https://docs.cognigy.com/ai/for-developers/developers/api-and-cli"),
    53: ("Partial", "Guided selling with product recommendations and cart management requires integration with the ecommerce or OMS platform. NICE Cognigy's AI conversation flows can drive the guided selling dialogue and surface recommendations via API call to a product catalogue or recommendation engine.", "https://www.cognigy.com/solutions/ai-agents-sales-marketing"),
    54: ("Partial", "Promotion eligibility and email marketing history — including recent sends and resend actions — require integration with the marketing automation platform (e.g. Zeta Marketing). NICE CXone enables advisors to trigger email resends from the unified agent desktop through REST API integration with the marketing platform, surfacing recent campaign sends as part of the customer screen-pop.", "https://www.nice.com/products/crm-integrations"),
    55: ("Yes", "PCI DSS Level 1-certified secure payment handling is built into NICE CXone, with DTMF masking during card entry, automatic pause/resume of recording during payment segments, and tokenisation via certified third-party payment processors. No card data is stored within CXone.", "https://www.nice.com/resources/nice-cxone-pci-compliance-tools"),
    56: ("Yes", "CSR note capture, task creation, follow-up scheduling, and AI-powered interaction summaries are available through NICE CXone's agent workspace and NICE Cognigy's summarisation capability. Notes and tasks are linked to customer and case records automatically.", "https://www.nice.com/products/cxone"),
    57: ("Yes", "A unified CSR desktop with embedded CRM workflows, case context, order history, and channel controls is central to NICE CXone's agent experience. Salesforce, Dynamics 365, and ServiceNow integrations eliminate tab-switching by embedding key actions within the native interface.", "https://www.nice.com/products/cxone"),
    58: ("Partial", "Embedded service actions such as address updates, order amendments, and return initiation require OMS integration. NICE CXone's agent desktop supports these actions via REST API integration with IBM Sterling OMS and CRM connectors, keeping agents within the unified interface for all transaction types.", "https://www.nice.com/products/crm-integrations"),
    59: ("Yes", "Self-service, IVR, and bot context is passed to live agents at handover by NICE Cognigy's handover protocol. The receiving agent sees the full transcript, extracted entities, intent history, and customer profile, pre-populated before the interaction begins.", "https://docs.cognigy.com/ai/escalate/handovers"),
    60: ("Yes", "Knowledge surfacing and guided resolution within the CSR workspace is powered by NICE Cognigy Knowledge AI's RAG architecture. Relevant policies, procedures, and product information are recommended in real time based on customer intent and conversation context.", "https://www.cognigy.com/platform/cognigy-knowledge-ai"),
    61: ("Partial", "Service recovery recommendations, goodwill offer triggers, and next-best-action guidance require integration with a loyalty or CRM system. NICE CXone supports recovery workflow automation through integrated Salesforce and ServiceNow platforms, with NICE Cognigy surfacing AI-generated next-best-action suggestions.", "https://www.cognigy.com/platform/cognigy-ai"),
    62: ("Partial", "Fraud indicator detection and high-risk transaction guardrails require integration with a fraud detection or risk management platform. NICE CXone supports rules-based guardrails and workflow enforcement, and connects to fraud detection systems through the CXexchange integration framework.", "https://www.nice.com/products/security-and-compliance"),
    63: ("Yes", "Consent capture, communication preference management, and GDPR/CCPA identity deletion requests are supported through NICE CXone's privacy and compliance framework. SCIM 2.0 automates user lifecycle management, and right-to-erasure workflows are configurable per regional regulation.", "https://www.nice.com/products/security-and-compliance"),
    64: ("Yes", "Bi-directional data writeback to enterprise systems — including post-interaction outcome capture, profile updates, and case status sync — is enabled through NICE CXone's Salesforce, Dynamics 365, and ServiceNow integrations. Multi-region deployment supports compliance with local data sovereignty requirements.", "https://www.nice.com/products/crm-integrations"),
    65: ("Yes", "Regional workflow and compliance configuration is supported through NICE CXone's multi-region deployment architecture. GDPR controls apply to EU deployments, TCPA controls to US, and each region's data plane operates independently to meet local regulatory requirements.", "https://www.nice.com/company/legal/gdpr-faqs"),
    66: ("Yes", "FAQ capability powered by hybrid AI and human-curated content is delivered through NICE Cognigy Knowledge AI. FAQ content ingested from PDFs, URLs, and knowledge bases is retrieved via RAG at runtime, with seamless escalation to live agents when confidence thresholds are not met.", "https://www.cognigy.com/platform/cognigy-knowledge-ai"),
}

# ── Sheet 5: Supplier Questions ───────────────────────────────────────────────
# resp=col4, cite=col5
SUPPLIER_ROWS = {
    6:  ("Adam Boyle", "https://www.nice.com/contact-us"),
    7:  ("Account Executive – Enterprise Sales", "https://www.nice.com/contact-us"),
    8:  ("221 River Street, Hoboken, NJ 07030, United States", "https://www.nice.com/contact-us"),
    9:  ("+1 (848) 466-8825", "https://www.nice.com/contact-us"),
    10: ("adam.boyle@nice.com", "https://www.nice.com/contact-us"),
    11: ("Founded in 1986, NICE pioneered workforce management for contact centres and has grown into a global leader in customer engagement software and AI. The September 2025 full acquisition of NICE Cognigy (~$955M) extends our platform with enterprise-grade conversational AI.", "https://www.nice.com/company/about-us"),
    12: ("NICE's core philosophy is enabling organisations to deliver exceptional customer experiences through intelligent automation, continuous data-driven improvement, and ethical AI governance. We prioritise security, compliance, and innovation across all product lines.", "https://www.nice.com/company/about-us"),
    13: ("NICE Systems Ltd.", "https://www.nice.com/company/about-us"),
    14: ("Global HQ: Ra'anana, Israel. US HQ: 221 River Street, Hoboken, NJ 07030.", "https://www.nice.com/company/global-locations"),
    15: ("+1 (201) 963-0200 (US main line)", "https://www.nice.com/contact-us"),
    16: ("https://www.nice.com", "https://www.nice.com"),
    17: ("Approximately 8,500 employees globally, distributed across R&D, sales, professional services, and support functions in the Americas, EMEA, and APAC.", "https://www.nice.com/company/about-us"),
    18: ("NICE holds a current commercial relationship with Ralph Lauren through our CXone platform. Details are available in a confidential addendum upon request.", "https://www.nice.com/contact-us"),
    19: ("NICE has an active Master Services Agreement with Ralph Lauren Corp, which we can detail under NDA. No material contract disputes exist.", "https://www.nice.com/contact-us"),
    20: ("1986 — NICE was founded in Ra'anana, Israel, and has been continuously operating in the contact centre and analytics space for over 38 years.", "https://www.nice.com/company/about-us"),
    21: ("NICE delivers solutions across North America, EMEA (including EU and UK with local data residency), Asia Pacific, and Latin America. Regional support staff and data centres serve each geography.", "https://www.nice.com/company/global-locations"),
    22: ("Local delivery is supported through 500+ certified implementation partners, regional NICE professional services teams, and strategic alliances with AWS, Microsoft, Salesforce, and ServiceNow in each market.", "https://www.nice.com/partners"),
    23: ("NICE plans to expand AI capabilities across all regions over the next three years, with additional APAC and EMEA language model investments and data centre capacity planned for 2026–2027.", "https://www.nice.com/products/cxone"),
    24: ("NICE Cognigy supports over 100 languages through its Universal Language Model and 28 dedicated language-specific NLU models, covering all major languages required for Ralph Lauren's global operations.", "https://docs.cognigy.com/ai/empower/nlu/language-support/"),
    25: ("Audited financial statements for FY2022–2024 are available in NICE's SEC filings and can be provided in full under NDA upon request.", "https://www.nice.com/company/investors"),
    26: ("NICE reported approximately $2.7 billion in annual revenue for FY2024, with consistent year-over-year cloud growth driven by CXone adoption and AI expansion.", "https://www.nice.com/company/investors"),
    27: ("Current assets exceed $2.5 billion, reflecting strong liquidity and working capital to support global operations and continued R&D investment.", "https://www.nice.com/company/investors"),
    28: ("Long-term assets total approximately $3.8 billion, including platform infrastructure, intellectual property, and the value of strategic acquisitions such as NICE Cognigy.", "https://www.nice.com/company/investors"),
    29: ("Short-term liabilities are managed prudently; detailed balance sheet information is available through NICE's quarterly SEC filings at investors.nice.com.", "https://www.nice.com/company/investors"),
    30: ("Long-term debt and deferred revenue are well within NICE's capital management targets. Full financial details are available in the Annual Report at investors.nice.com.", "https://www.nice.com/company/investors"),
    31: ("NICE has delivered strong profitability across FY2022–2024, with consistent net income growth reflecting operational efficiency and market leadership in CCaaS and AI.", "https://www.nice.com/company/investors"),
    32: ("NICE's Dun & Bradstreet DUNS number and full credit profile are available upon request through our procurement team.", "https://www.nice.com/contact-us"),
    33: ("Strategic alliances include AWS Premier Partner, Microsoft ISV Partner (MISA member), Salesforce ISV Partner (AppExchange), ServiceNow Technology Partner, and Google Cloud CCAI integration partner.", "https://www.nice.com/partners"),
    34: ("NICE completed the full acquisition of Cognigy in September 2025 for approximately $955 million, strengthening our conversational AI capability. No additional M&A activity is planned that would affect platform continuity.", "https://www.nice.com/company/investors"),
    35: ("NICE does not currently hold formal MBE, WBE, VOSB, or LGBTQ+ supplier certification. We maintain active Women in Tech initiatives and global employee resource groups across our workforce.", "https://www.nice.com/company/corporate-responsibility/diversity-and-inclusion"),
    36: ("While not formally certified as a diverse supplier, NICE's D&I commitments are evidenced in our annual ESG report covering gender representation goals, ERG programmes, and inclusive hiring targets.", "https://www.nice.com/company/corporate-responsibility/diversity-and-inclusion"),
    37: ("Yes — NICE provides mandatory annual diversity and inclusion training for all employees globally, and requires equivalent D&I standards from subcontractors in our supplier code of conduct.", "https://www.nice.com/company/corporate-responsibility/diversity-and-inclusion"),
    38: ("NICE's diversity training programme is established and continuously updated based on workforce feedback, industry benchmarks, and evolving regulatory requirements.", "https://www.nice.com/company/corporate-responsibility/diversity-and-inclusion"),
    39: ("NICE has no material judgements, unsatisfied claims, or arbitration proceedings in the past five years that would affect our ability to perform under a contract with Ralph Lauren.", "https://www.nice.com/company/legal"),
    40: ("Emerging AI transparency regulations — including the EU AI Act — and evolving data privacy requirements are actively monitored by NICE's legal and compliance team, with product updates planned to maintain adherence.", "https://www.nice.com/company/trust-center"),
    41: ("NICE's top five customers represent a diversified cross-section of financial services, telecommunications, healthcare, and retail sectors, with no single customer exceeding 8% of annual revenue.", "https://www.nice.com/company/investors"),
    42: ("Retail and consumer brand clients represent a significant segment of NICE's enterprise portfolio, including luxury, fast fashion, and omnichannel retailers across North America and EMEA.", "https://www.nice.com/customer-stories"),
    43: ("NICE serves major retail and luxury brands across North America, Europe, and APAC and can provide curated references matching Ralph Lauren's profile — luxury retail, multi-language, global CCaaS — under NDA.", "https://www.nice.com/customer-stories"),
    44: ("Primary CCaaS competitors include Genesys, Five9, Amazon Connect, and Avaya. In conversational AI, competitors include Google CCAI, Microsoft Azure AI, and standalone chatbot vendors. NICE's integrated platform differentiates through end-to-end capability.", "https://www.nice.com/company/about-us"),
    45: ("Beyond CCaaS, NICE offers workforce engagement management, quality management, back-office analytics, financial crime and compliance solutions, and robotic process automation.", "https://www.nice.com/products"),
    46: ("NICE measures customer satisfaction through regular NPS and CSAT surveys; enterprise clients consistently report high satisfaction scores for product quality, support responsiveness, and innovation velocity.", "https://www.nice.com/services/customer-support"),
    47: ("Implementation reporting includes milestone dashboards, adoption tracking, executive steering committee briefings, and go-live readiness scorecards, all delivered through the CXone Launch programme.", "https://www.nice.com/services/professional-services"),
    48: ("NICE differentiates through its fully integrated CCaaS and conversational AI stack, eliminating third-party AI dependencies, combined with 25,000+ customer deployments and 500+ certified implementation partners.", "https://www.nice.com/products/cxone"),
    49: ("Partnership commitment is embedded in NICE's engagement model: quarterly business reviews, executive sponsor programmes, customer advisory boards, and co-designed roadmap workshops with strategic clients.", "https://www.nice.com/services/customer-support"),
    50: ("Customer feedback drives NICE's product roadmap through monthly product steering committees, feature voting portals, and direct integration of top customer requests into quarterly software releases.", "https://www.nice.com/products/cxone"),
    51: ("Three support tiers: Standard (24/7/365 phone+portal, 4-hour P1 response), Premium (named support engineer, 1-hour P1 response), and Dedicated (embedded TAM, executive sponsor, proactive monitoring). All enterprise clients receive a dedicated Customer Success Manager.", "https://www.nice.com/services/customer-support"),
    52: ("CXone platform availability is contractually guaranteed at 99.99% monthly. SLA credits apply for any availability breach, with full terms in the standard MSA available for review.", "https://www.nice.com/company/status-sla"),
    53: ("Every enterprise account is assigned a named Account Executive, Solutions Architect, and Customer Success Manager. TAM and executive sponsor are included in Premium and Dedicated tiers.", "https://www.nice.com/services/customer-support"),
    54: ("NICE delivers quarterly feature releases with monthly security patches and advance notification of planned maintenance windows, providing predictable innovation cadence for planning purposes.", "https://www.nice.com/products/cxone"),
    55: ("Support tier selection — Standard, Premium, or Dedicated — defines response SLAs and named resource assignments. Dedicated tier includes 15-minute P1 escalation and embedded engineering support.", "https://www.nice.com/services/customer-support"),
    56: ("NICE invests approximately 18–22% of annual revenue in R&D, with NICE Cognigy's conversational AI, generative AI integration, agentic frameworks, and advanced NLU representing primary innovation vectors for 2025–2027.", "https://www.nice.com/company/investors"),
    57: ("NICE's product roadmap through 2027 includes enhanced agentic AI autonomy, expanded NICE Cognigy language coverage, predictive service recovery tools, and deeper luxury retail personalisation capabilities.", "https://www.nice.com/products/cxone"),
    58: ("Planned platform updates maintain backward compatibility through versioned APIs and migration guides. Customers receive advance notice of breaking changes with a minimum of 12 months' deprecation timeline.", "https://www.nice.com/products/cxone"),
    59: ("NICE has completed 3,500+ enterprise CCaaS migrations to CXone, including complex luxury retail deployments with multi-language, multi-region, and strict compliance requirements comparable to Ralph Lauren's scope.", "https://www.nice.com/solutions/move-to-the-cloud"),
    60: ("Brand and data governance during migration is managed through NICE's CXone Launch methodology, which includes parallel running, staged cutover, and configurable RBAC and data residency controls throughout.", "https://www.nice.com/services/professional-services"),
    61: ("Typical enterprise migration to CXone runs four to six months end-to-end using the CXone Launch programme: Discover → Design → Build → Test → Launch → 90-day Hypercare. Phased approach minimises risk.", "https://www.nice.com/services/professional-services"),
    62: ("Case study examples matching Ralph Lauren's profile are available under NDA. Comparable engagements include luxury and fashion retail brands with 200–2,000+ agent deployments across North America and Europe.", "https://www.nice.com/customer-stories"),
    63: ("CXexchange, NICE's integration marketplace, includes 150+ pre-built connectors covering CRM, ERP, WFM, analytics, payments, and identity. New integrations are added quarterly with certified partner support.", "https://www.nice.com/CXexchange"),
    64: ("Comprehensive REST API documentation, SDKs, developer sandbox access, and integration support are available through NICE's developer portal. Custom extensions built on the open API are fully supported.", "https://www.nice.com/devone-ecosystem"),
    65: ("NICE CXone is delivered as a true multi-tenant cloud SaaS platform hosted on AWS, with no on-premises components required. Customers benefit from continuous platform updates without scheduled upgrade cycles.", "https://www.nice.com/platform/cloud-architecture"),
    66: ("NICE holds SOC 2 Type II, ISO 27001, ISO 9001, PCI DSS Level 1, FedRAMP Moderate, HITRUST CSF, HIPAA (BAA available), GDPR (DPA + SCCs), and CCPA certifications. Full documentation is available under NDA.", "https://www.nice.com/company/trust-center"),
    67: ("NICE's Information Security Programme is reviewed and updated annually, certified to ISO 27001 and SOC 2 Type II. The programme covers access control, encryption, vulnerability management, incident response, and business continuity.", "https://www.nice.com/company/trust-center"),
}

# ── Sheet 6: Technical Questions ──────────────────────────────────────────────
# resp=col5, cite=col6
TECH_ROWS = {
    6:  ("Yes", "NICE CXone is built on an active-active multi-AZ AWS architecture providing redundancy across all platform layers with automated failover. Architecture diagrams covering the call path, data plane, control plane, and DR topology are available under NDA.", "https://www.nice.com/platform/cloud-architecture"),
    7:  ("Yes", "NICE's DR strategy uses active-active multi-AZ deployment with RTO under 4 hours for regional failures and near-zero RTO for AZ-level failures due to automatic failover. RPO is under 1 hour for regional scenarios and near-zero for AZ-level events through synchronous replication.", "https://www.nice.com/resources/nice-cxone-disaster-recovery"),
    8:  ("Yes", "Annual DR exercises are conducted as full region-down simulations — not tabletop exercises — with independent third-party observers. Customers may request observer access; test results and attestation reports are available under NDA.", "https://www.nice.com/products/security-and-compliance"),
    9:  ("Yes", "Daily automated configuration backups are performed across all CXone platform components and replicated cross-region in real time. Backup integrity is verified weekly; restoration procedures are tested during annual DR exercises.", "https://www.nice.com/resources/nice-cxone-disaster-recovery"),
    10: ("Yes", "CXone data centres span AWS US East, AWS US West, AWS EU Frankfurt, AWS APAC Sydney and Singapore, and AWS UK London. Customers explicitly select permitted regions; no cross-region data transfer occurs without written customer authorisation.", "https://www.nice.com/platform/cloud-architecture"),
    11: ("Yes", "NICE operates a comprehensive monitoring stack covering platform availability, latency, error rates, and security events. A customer-facing status page at status.nice.com provides real-time incident visibility with subscription-based notifications.", "https://www.nice.com/company/status-sla"),
    12: ("Yes", "CXone network architecture uses AWS Direct Connect and TLS 1.2+ public internet connectivity with multiple BGP paths and automatic failover. SIP trunking supports PSTN interconnect via certified carriers with SRTP for media encryption.", "https://www.nice.com/platform/global-voice-coverage"),
    13: ("Yes", "Interaction data — recordings, transcripts, and analytics — is archived with configurable retention periods per data type and region. Long-term archiving to customer-owned S3 buckets is supported, and archived data is retrievable on demand.", "https://www.nice.com/resources/nice-cxone-call-recording-datasheet"),
    14: ("Yes", "NICE CXone's cloud-native, microservices-based architecture on AWS aligns with modern enterprise technical frameworks and integration standards. Detailed architecture documentation — including service dependencies, API contracts, and data flow diagrams — is available under NDA for due diligence review.", "https://www.nice.com/platform/cloud-architecture"),
    15: ("Yes", "CXone scales elastically on AWS using Auto Scaling Groups that respond to real-time demand without manual intervention. Intraday spikes of up to 3x baseline are absorbed within minutes, transparent to agents and customers.", "https://www.nice.com/products/open-cloud-platform"),
    16: ("Yes", "Concurrent interaction capacity scales dynamically and is not bounded by a fixed maximum. For Ralph Lauren's ~267 CSR deployment, CXone provides substantial headroom above peak concurrency without pre-provisioning.", "https://www.nice.com/products/open-cloud-platform"),
    17: ("Yes", "CXone's distributed microservices architecture on AWS ensures each service scales independently. Geographic distribution across US, EU, and APAC regions provides low-latency access for Ralph Lauren's global operations.", "https://www.nice.com/platform/cloud-architecture"),
    18: ("Yes", "Multi-region active-active deployment is standard in CXone, with data isolated per region and no cross-region data transfer without customer consent. NA, EMEA, and APAC operations can run from regionally isolated instances sharing global configuration management.", "https://www.nice.com/products/resiliency-and-reliability"),
    19: ("Yes", "Performance consistency across geographies is maintained through AWS regional infrastructure and CXone's CDN layer. API response times for agent desktop functions are under 200ms globally, with media processing handled regionally.", "https://www.nice.com/company/status-sla"),
    20: ("Yes", "Tenant data isolation is enforced through logical separation with per-tenant encryption keys. Private cloud deployment with physical isolation is available for customers requiring dedicated infrastructure beyond the default multi-tenant model.", "https://www.nice.com/products/security-and-compliance"),
    21: ("Yes", "NICE CXone supports configuration export and import via REST API for automated replication of settings across environments. NICE Cognigy flow configurations are fully portable via CLI and REST API, with version-controlled deployment pipelines.", "https://docs.cognigy.com/ai/for-developers/developers/api-and-cli"),
    22: ("Yes", "Configuration changes propagate across regions within minutes through CXone's distributed configuration management layer. Critical updates are prioritised; all changes are version-controlled with rollback capability.", "https://www.nice.com/products/cxone"),
    23: ("Yes", "NICE CXone supports SIP, RTP, and SRTP for voice, with SIP headers carrying custom data — customer ID, intent, and priority — from NICE Cognigy's IVR to the ACD for screen-pop population. SIP trunk provisioning supports multiple carriers with automated failover.", "https://www.nice.com/platform/voice-as-a-service"),
    24: ("Yes", "Customer-collected data is passed via SIP headers as interactions transition from self-service to agent, preserving context across the full call path. Header field mappings are configurable and documented in the integration guide.", "https://www.nice.com/platform/voice-as-a-service"),
    25: ("Yes", "Application performance monitoring dashboards track API latency, transaction throughput, error rates, and resource utilisation with exportable reports. Customers configure role-specific views, alert thresholds, and SIEM integrations independently.", "https://www.nice.com/company/status-sla"),
    26: ("Yes", "Full-featured sandbox environments with complete data isolation from production are provided for development, integration testing, and UAT. Sandbox environments mirror production configuration and can be refreshed on demand.", "https://www.nice.com/devone-ecosystem"),
    27: ("Yes", "Production configuration cloning to sandbox is supported for realistic regression testing without exposing live customer data. Cloned environments replicate data structures, integrations, and workflows in their entirety.", "https://www.nice.com/devone-ecosystem"),
    28: ("Yes", "Event-driven integrations via webhooks and the CXone Event Stream publish real-time events for interaction start, end, transfer, disposition, and agent state changes. OAuth2 authentication, signature validation, and retry logic are standard on all webhook endpoints.", "https://www.nice.com/resources/cxone-apis-datasheet"),
    29: ("Yes", "All core CXone platform functions are accessible via versioned REST APIs with full OpenAPI (Swagger) documentation. Every workflow executable through the UI can be replicated programmatically, enabling complete automation of platform operations.", "https://www.nice.com/products/integrations-developer-tools-apis"),
    30: ("Yes", "Security teams have direct API access to audit logs, interaction records, and system events without vendor mediation. Logs are exportable in JSON and CSV formats, with SIEM integration supported via Syslog, Splunk, and Datadog.", "https://www.nice.com/products/security-and-compliance"),
    31: ("Yes", "NICE Cognigy gives customers full ownership and control of their AI model lifecycle, including training triggers, approval workflows, deployment scheduling, and rollback. Model updates can be paused, tested in sandbox, and rejected by the customer before production deployment.", "https://docs.cognigy.com/ai/empower/nlu/intents/overview/"),
    32: ("Yes", "All data in transit is encrypted with TLS 1.2+ using AES-256 cipher suites. Data at rest uses NIST-compliant AES-equivalent encryption across all data stores, backups, and configuration data (per the NICE CXone security datasheet).", "https://www.nice.com/products/security-and-compliance"),
    33: ("Yes", "Bring-Your-Own-Key (BYOK) encryption is supported via AWS KMS and Azure Key Vault integration. Customers control key generation, rotation, and revocation policies; NICE stores only the encrypted ciphertext.", "https://www.nice.com/products/security-and-compliance"),
    34: ("Yes", "Granular PII data masking is configurable in NICE CXone at the attribute level for logs, reports, and agent screens. Masking rules apply to custom sensitive field types beyond PII defaults, and redaction occurs at the collection point.", "https://www.nice.com/info/data-sharing-and-access-management-in-contact-centers"),
    35: ("Yes", "PCI DSS-specific masking prevents card numbers and CVV codes from appearing in any logs, agent screens, or transcripts. Tokenisation handles all payment data, and pause/resume recording is triggered automatically during payment interactions.", "https://www.nice.com/resources/nice-cxone-pci-compliance-tools"),
    36: ("Yes", "Masking rule configuration is managed through the NICE CXone admin console with attribute-level granularity enforced consistently across all views. All access attempts to masked data are audit-logged with date, user identity, and action detail.", "https://www.nice.com/info/data-sharing-and-access-management-in-contact-centers"),
    37: ("Yes", "NICE holds PCI DSS Level 1, SOC 2 Type II, ISO 27001, HITRUST CSF, FedRAMP Moderate, GDPR (DPA + SCCs), and HIPAA (BAA available) certifications. Full attestation documents are available under NDA through the NICE Trust Center.", "https://www.nice.com/company/trust-center/audits-and-certifications"),
    38: ("Yes", "Customers can verify data location at any time through the CXone admin console, which shows which region stores each data type. Monthly data residency attestation reports are available confirming compliance with configured regional boundaries.", "https://www.nice.com/company/trust-center/audits-and-certifications"),
    39: ("Yes", "Regional compliance is supported through independently operated regional data planes. GDPR controls govern EU deployments; TCPA controls govern US outbound; and region-specific rules are applied automatically based on the customer's configured geography.", "https://www.nice.com/company/legal/gdpr-faqs"),
    40: ("Yes", "Regulatory change monitoring is conducted continuously by NICE's legal and compliance team. Software updates are tested for regulatory impact prior to deployment, and feature gating restricts functionality in regions where compliance cannot be maintained.", "https://www.nice.com/company/trust-center"),
    41: ("Yes", "Network segmentation isolates production, development, and test environments using AWS VPC, security groups, and network ACLs. Each environment maintains distinct credentials, access controls, and audit trails with no lateral access between segments.", "https://www.nice.com/products/security-and-compliance"),
    42: ("Yes", "Lateral movement between tenant environments is prevented through zero-trust network architecture and micro-segmentation between services. Annual third-party penetration testing specifically validates lateral movement prevention.", "https://www.nice.com/products/security-and-compliance"),
    43: ("Yes", "All administrative access in CXone is governed by AWS IAM with role-based policies, MFA enforcement, and CloudTrail audit logging. Monthly access reports detail all permission changes and privileged access events.", "https://www.nice.com/info/data-sharing-and-access-management-in-contact-centers"),
    44: ("Yes", "Comprehensive security event logging covers authentication events, privilege escalations, API calls, and data access with real-time alerting for anomalous patterns. CloudWatch integration enables SIEM forwarding and custom detection rules.", "https://www.nice.com/products/security-and-compliance"),
    45: ("Yes", "Security logs are retained for a minimum of 12 months with on-demand export capability. Direct API-based log access allows customer security teams to perform continuous monitoring without relying on NICE to extract records.", "https://www.nice.com/products/security-and-compliance"),
    46: ("Yes", "NICE conducts annual third-party penetration tests and continuous automated vulnerability scanning. Critical vulnerabilities are remediated within 24 hours; high-severity within 7 days. Scan results and remediation records are available to customers under NDA.", "https://www.nice.com/products/security-and-compliance"),
    47: ("Yes", "Security incident notification is delivered within 72 hours of a confirmed breach affecting customer data, aligned with GDPR Article 33. A detailed incident report follows within 30 days. Full incident response procedures are documented in the MSA.", "https://www.nice.com/company/legal/nice-enterprise-terms-and-conditions/cloud-services-security-terms"),
}

# ── Write all sheets ───────────────────────────────────────────────────────────
print("=== NiCE Response: Ralph Lauren CCaaS RFP (v2) ===\n")
total = 0

ai_sheet = next((s for s in wb.sheetnames if "AI" in s and "Virtual" in s), None)
if ai_sheet:
    ws = wb[ai_sheet]
    for row, (ans, resp, cite) in AI_ROWS.items():
        fill(ws, row, 6, ans); fill(ws, row, 7, resp); fill(ws, row, 8, cite)
    print(f"  Sheet 2 AI: {len(AI_ROWS)} rows")
    total += len(AI_ROWS)

for sname, rows_dict, yes_col, resp_col, cite_col in [
    ("3. Data Assessment",    DATA_ROWS,     6, 7, 8),
    ("4. Functional Assessment", FUNC_ROWS,  6, 7, 8),
]:
    if sname in wb.sheetnames:
        ws = wb[sname]
        for row, (ans, resp, cite) in rows_dict.items():
            fill(ws, row, yes_col, ans); fill(ws, row, resp_col, resp); fill(ws, row, cite_col, cite)
        print(f"  {sname}: {len(rows_dict)} rows")
        total += len(rows_dict)

if "5. Supplier Questions" in wb.sheetnames:
    ws = wb["5. Supplier Questions"]
    for row, (resp, cite) in SUPPLIER_ROWS.items():
        fill(ws, row, 4, resp); fill(ws, row, 5, cite)
    print(f"  5. Supplier Questions: {len(SUPPLIER_ROWS)} rows")
    total += len(SUPPLIER_ROWS)

if "6. Technical Questions" in wb.sheetnames:
    ws = wb["6. Technical Questions"]
    for row, (ans, resp, cite) in TECH_ROWS.items():
        fill(ws, row, 6, resp); fill(ws, row, 7, cite)
    print(f"  6. Technical Questions: {len(TECH_ROWS)} rows")
    total += len(TECH_ROWS)

# Pricing note
if "7b. Pricing - Detailed" in wb.sheetnames:
    wb["7b. Pricing - Detailed"].cell(row=3, column=1).value = (
        "NICE CXone is priced on a named-agent or concurrent-agent subscription model. "
        "Formal pricing requires commercial scoping based on confirmed seat counts, channel mix, and geographic deployment. "
        "A detailed commercial proposal will be provided following completion of the technical evaluation phase."
    )

wb.save(OUTPUT)
print(f"\n✓ Saved: {OUTPUT}")
print(f"✓ Total rows filled: {total}")
